modified the system/Makefile to initialize & update submodules if they do not exist

diff --git a/system/Makefile b/system/Makefile
--- a/system/Makefile
+++ b/system/Makefile
@@ -3,12 +3,27 @@ SLOWDASH_DIR = $(shell cd ..; pwd)
 SLOWDASH_BIN = $(SLOWDASH_DIR)/bin/slowdash
 SLOWDASH_ENV = $(SLOWDASH_DIR)/bin/slowdash-bashrc
 PYTHON = $(shell which python3)
+GIT = $(shell which git)
 
 
 all:
 	@if [ x$(PYTHON) = x ]; then \
 		echo 'unable to find python3 (`which python3` returned null)'; \
 		exit 255; \
+	fi
+
+	@if [ ! -f $(SLOWDASH_DIR)/system/web/jagaimo/jagaimo.mjs ]; then \
+		if [ x$(GIT) = x ]; then \
+			echo 'submodules not '; \
+			exit 255; \
+		fi; \
+		$(GIT) submodule update --init --recursive; \
+		if [ ! -f $(SLOWDASH_DIR)/system/web/jagaimo/jagaimo.mjs ]; then \
+			echo 'unable obtain to submodules'; \
+			exit 255; \
+		fi; \
+		echo "submodules updated"; \
+		echo ""; \
 	fi
 
 	@if [ ! -d $(SLOWDASH_DIR)/bin ]; then mkdir $(SLOWDASH_DIR)/bin; fi
@@ -27,7 +42,7 @@ all:
 	@echo "Make successful"
 	@echo ""
 	@echo "- executable files are copied to $(SLOWDASH_DIR)/bin"
-	@echo "- including this bin dir to your PATH might be useful, either by"
+	@echo "- including this bin directory to your PATH variable might be useful, either by"
 	@echo '    export PATH=$${PATH}:$(SLOWDASH_DIR)/bin'
 	@echo '        or'
 	@echo '    source $(SLOWDASH_DIR)/bin/slowdash-bashrc'
